hotel_name: 'One Hill Motel Sarl'
hotel_logo: 'one_hill_motel.JPG'
hotel_address_line1: 'Near Kisimenti, Remera'
hotel_address_line2: 'Ubwiza Avenue'
hotel_address_line3: 'Kigali'
hotel_email: 'info@onehillmotel.com'
hotel_website: 'http://www.onehillmotel.com'
hotel_phone: '+250 788849494'
hotel_time_zone: "Africa/Cairo"
hotel_checkout_hour: 12
